app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns = [
    path('csk/',csk,name='csk'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name ='app2'

urlpatterns =[

    path('dhoni/',dhoni,name='dhoni')
]

specific_urlnavigation/urls.py
from django.contrib import admin
from django.urls import path,include

import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def csk(request):
    return render(request,'csk.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

templates/csk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>csk</title>
</head>
<body>
    <center><h1>CSK</h1></center>
    <center><h1><a href="{% url 'app2:dhoni' %}">click here</a></h1></center>
</body>
</html>

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>DHONI</h1></center>
    <center><h1><a href="{% url 'app1:csk' %}"> click here</a></h1></center>
</body>
</html>